#!/bin/bash

# ==========================================
# Setup & Configuration
# ==========================================

# strict mode: exit on error, undefined vars, or pipe failures
set -euo pipefail

# Global Constants
DEV_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare -A RESOURCE_PATH

RESOURCE_PATH["XDG_DATA_HOME"]="$HOME/.local/share"
RESOURCE_PATH["XDG_CACHE_HOME"]="$HOME/.local/cache"
RESOURCE_PATH["XDG_CONFIG_HOME"]="$HOME/.config"
RESOURCE_PATH["DOT_FILES"]="$DEV_HOME/dot-files"
RESOURCE_PATH["PKG_SCRIPT"]="${RESOURCE_PATH[DOT_FILES]}/packages"
RESOURCE_PATH["BASHRC_SRC"]="${RESOURCE_PATH[DOT_FILES]}/bashrc"
RESOURCE_PATH["BASHRC_DST"]="$HOME/.bashrc"
RESOURCE_PATH["FONT_SRC"]="$DEV_HOME/resources/fonts"
RESOURCE_PATH["FONT_DST"]="${RESOURCE_PATH[XDG_DATA_HOME]}/fonts"
RESOURCE_PATH["AUDIO_SRC"]="$DEV_HOME/resources/media/audio"
RESOURCE_PATH["AUDIO_DST"]="${RESOURCE_PATH[XDG_DATA_HOME]}/audio"
RESOURCE_PATH["TMUX_SRC"]="$DEV_HOME/tmux"
RESOURCE_PATH["TMUX_DST"]="${RESOURCE_PATH[XDG_CONFIG_HOME]}/tmux"
RESOURCE_PATH["TPM_SCRIPT"]="${RESOURCE_PATH[TMUX_DST]}/plugins/tpm/bin/install_plugins"
RESOURCE_PATH["VIM_SRC"]="$DEV_HOME/vim"
RESOURCE_PATH["VIM_DST"]="$HOME/.vim"

# Colors for logging
GREEN='\e[92m'
BLUE='\e[34m'
PURPLE='\e[35m'
YELLOW='\e[93m'
RED='\e[91m'
GRAY='\e[90m'
WHITE='\e[97m'
END='\e[0m'

WARN="(${YELLOW}*${END})"
INFO="(${WHITE}i${END})"
ERROR="(${RED}!${END})"
QESTN="(${BLUE}?${END})"

# ==========================================
# Utility Functions
# ==========================================

preflight_check() {
 
 echo
 echo -e "$INFO Checking referential integrity..."
 echo

 for RESOURCE in "${!RESOURCE_PATH[@]}"; do 
  if [[ ! -x "${RESOURCE_PATH[$RESOURCE]}" ]]; then
   echo -e "$ERROR Resource not found: ${YELLOW}$RESOURCE${END}=${WHITE}${RESOURCE_PATH[$RESOURCE]}${END}"
  fi
 done

 # Ensure sudo permissions upfront to prevent timeout
 sudo -v
 
 # Safety check for running Tmux
 if [[ -n "${TMUX:-}" ]]; then
  echo
  echo -e "$ERROR Terminate ${YELLOW}Tmux${END} process before proceeding"
  echo
  exit 1
 fi

 echo
 echo -e "${GRAY}Initializing Dev Environment${END}"
 echo

 # Critial for for other scripts to find
 echo -e "$INFO Setting env ${GREEN}DEV_HOME${END}=${WHITE}$DEV_HOME${END}"

 export "DEV_HOME=$DEV_HOME"

 if ! grep "export DEV_HOME=" "$HOME/.bashrc" > /dev/null 2>&1; then

  BASH_RC="$HOME/.bashrc"
  EXPORT_CMD="export DEV_HOME=$DEV_HOME"

  echo -e "$INFO Adding ${GREEN}DEV_HOME${END} export to $BASH_RC"

  # Writting export command to the users bashrc file
  echo >> "$BASH_RC"
  echo "# Path to dev.environment directory" >> "$BASH_RC"
  echo "$EXPORT_CMD" >> "$BASH_RC"
  echo >> "$BASH_RC"

 fi
}

link_resource() {

 local SRC_RESOURCE="$1"
 local DST_RESOURCE="$2"

 local DST_PATH=$(dirname "$DST_RESOURCE")
 echo -e "${INFO} Ensuring path integrity: ${GRAY}${DST_PATH}${END}"
 mkdir -p "$DST_PATH"

 echo -e "${INFO} Removing/Unlinking any existing resources: ${WHITE}${DST_PATH}${END}"
 if [[ -e "$DST_RESOURCE" || -L "$DST_RESOURCE" ]]; then
  rm -rf "$DST_RESOURCE"
 fi

 ln -s "$SRC_RESOURCE" "$DST_RESOURCE"
 echo -e "${INFO} ${GREEN}Linked${END}: ${WHITE}${DST_RESOURCE}${END} -> ${GREEN}${SRC_RESOURCE}${END}"
}

install_fonts() {

 echo -e "Installing fonts..."

 # Ensure destination directory exists
 echo -e "${GRAY}Ensuring desitination path exists :${END} ${WHITE} ${RESOURCE_PATH[FONT_DST]} ${END}"
 mkdir -p "${RESOURCE_PATH[FONT_DST]}"

 echo -e "${GRAY}"
 tar -xvf "${RESOURCE_PATH[FONT_SRC]}/fonts.tar" -C "${RESOURCE_PATH[FONT_DST]}"
 echo -e "${END}"

 if command -v fc-cache &>/dev/null; then
  fc-cache -f
  echo -e "${WHITE}Font cache updated.${END}"
 else
  echo -e "${YELLOW}fc-cache not found, attempting to install...${END}"
  if sudo apt install fc-cache &> /dev/null; then
   fc-cache -f
  fi
 fi
}

install_resources() {

 echo
 echo -e "${WHITE}Installing resources...${END}"

 echo -e "${GRAY}Ensuring desitination path exists :${END} ${WHITE} ${RESOURCE_PATH[AUDIO_DST]} ${END}"
 mkdir -p "${RESOURCE_PATH[AUDIO_DST]}" 

 # Copy content and fix permissions
 sudo cp -rfT "${RESOURCE_PATH[AUDIO_SRC]}" "${RESOURCE_PATH[AUDIO_DST]}"
 sudo chown -R "$USER:$USER" "${RESOURCE_PATH[AUDIO_DST]}"
 
 echo -e "$INFO Audio resources installed to ${GREEN}${RESOURCE_PATH[AUDIO_DST]}${END}"
}

setup_tmux() {

 echo -e "${GRAY}Configuring Tmux...${END}"

 # Link the main configuration directory
 link_resource "${RESOURCE_PATH[TMUX_SRC]}" "${RESOURCE_PATH[TMUX_DST]}"

 if [[ -x "${RESOURCE_PATH[TPM_SCRIPT]}" ]]; then

  echo -e "$INFO Running Tmux Plugin-Manager installation..."

  # Running inside a subshell to avoid directory changing side-effects
  ("${RESOURCE_PATH[TPM_SCRIPT]}")
 else
  echo -e "$ERROR TPM installer not found at path: ${RESOURCE_PATH[TPM_SCRIPT]}"
  exit 1
 fi
}

setup_vim() {

 echo -e "$INFO ${GRAY}Configuring Vim...${END}"
 link_resource "${RESOURCE_PATH[VIM_SRC]}" "${RESOURCE_PATH[VIM_DST]}"
}

configure_bash() {

 echo -e "$INFO ${GRAY}Configuring Bash...${END}"

 declare -A MAPPER

 MAPPER["aliases"]=".bash_aliases"
 MAPPER["functions"]=".bash_functions"
 MAPPER["completions"]=".bash_completions"
 MAPPER["bashrc"]=".bashrc"

 # Link dot files to user's $HOME directory
 for FILE in "${!MAPPER[@]}"; do

  RESOURCE_SRC="${RESOURCE_PATH[DOT_FILES]}/${FILE}"
  
  if [[ ! -f "${RESOURCE_SRC}" ]]; then
   echo -e "$ERROR Failure referencing source file: ${YELLOW}${RESOURCE_SRC}${END}"
   exit 1
  fi

  RESOURCE_DST="${HOME}/${MAPPER[$FILE]}"

  link_resource "${RESOURCE_SRC}" "${RESOURCE_DST}"
  echo -e "$INFO Sourcing script ${BLUE}$RESOURCE_DST${END}"
  source "$RESOURCE_DST"
 done
 
 echo "Completed linking bash resources"
 echo

 TARGETS=("aliases" "functions" "completions")

 for TARGET in "${TARGETS[@]}"; do

  ENTRY="${RESOURCE_PATH[DOT_FILES]}/$TARGET"

  if ! grep "source $ENTRY" "$HOME/.bashrc" > /dev/null 2>&1; then
   echo -e "$INFO ${GRAY}Adding source entry ${END}${YELLOW}$TARGET${END}${GRAY} to bashrc${END}"
   echo "# Path to dev.environment $TARGET file" >> "$HOME/.bashrc"
   echo "source $TARGET" >> "$HOME/.bashrc"
   echo >> "$HOME/.bashrc"
  fi
 done

 if [[ ! -f "${RESOURCE_PATH[PKG_SCRIPT]}" ]]; then
  echo -e "$ERROR Resource '${YELLOW}package${END}' was missing. Terminating..."
  exit 1
 else
  echo -e "$INFO Package script '${BLUE}package${END}' found!"

  # Execute the script
  ${RESOURCE_PATH["PKG_SCRIPT"]}

 fi
}

# ==========================================
# Main Execution
# ==========================================

main() {

 preflight_check

 install_fonts
 install_resources
 
 configure_bash

 setup_vim
 setup_tmux

 echo -e "Reloading shell configuration..."
 source "$HOME/.bashrc" || true

 echo
 echo -e "${GRAY}Setup Complete!${END}"
 echo
 echo -e "${WHITE} ⚠️  Restart Terminal ⚠️  ${END}"
 echo
}

# Execute
main "$@"
