#!/bin/bash

#Safety & Strict Mode
set -uo pipefail

DRY_RUN="false"

# Temp directories
TEMP_DEV_INIT_DIR="/tmp/dev-env"
LOG_FILE="$TEMP_DEV_INIT_DIR/dev-env.log"

# Create if not present
if [[ ! -f "$TEMP_DEV_INIT_DIR" ]]; then
 mkdir -p "/tmp/dev-env" >/dev/null 2>&1
fi

#Global Variables
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_PATH="$TEMP_DEV_INIT_DIR/env-backup-${TIMESTAMP}.tar"
TMUX_DST_DIR="$HOME/.config/tmux"

# --- Helper Function ---
function log() {
 #echo -e "$@" | tee -a "$LOG_FILE"
 echo -e "$@"
}

# --- Helper Function ---
function error_exit() {
 log "❌ Critical Error: $1"
 exit 1
}

# If DRY_RUN is false, it executes it using eval (to handle pipes/redirects).
function safe_execute() {

 local cmd="$*"

 if [[ "$DRY_RUN" == "true" ]]; then
  log "⚙️  [DRY RUN] Execute: $cmd"
  return 0 # Always return success in dry run so the script continues
 else
  # specific check for 'exec' which replaces the shell
  if [[ "$cmd" == exec* ]]; then
   eval "$cmd"
  else
   eval "$cmd"
  fi
 fi
}

function check_dependencies() {

 local deps=("tmux" "tar" "git" "fc-cache")

 for cmd in "${deps[@]}"; do
  if ! command -v "$cmd" &>/dev/null; then
   if [[ "$DRY_RUN" == "true" ]]; then
    log "⚠️  [DRY RUN] Missing dependency '$cmd' (ignoring for test)"
   else
    error_exit "Required command '$cmd' is not installed."
   fi
  fi
 done
}

function install_fonts() {

 local SRC_FONT_DIR="$SRC_DIR/fonts"
 local DST_FONT_DIR="$HOME/.local/share/fonts"

 echo
 log "💾  Installing Fonts..."

 # Ensure destination directory exits
 safe_execute "mkdir -p \"$DST_FONT_DIR\""

 safe_execute "cp -a \"$SRC_FONT_DIR/.\" \"$DST_FONT_DIR\""
 for font in "$SRC_FONT_DIR"/*; do
  log "📁  [DRY RUN] Execute: cp -a $font to $DST_FONT_DIR"
 done

 safe_execute "fc-cache -f"
}

function tmux_fix() {

 log "⟳   Initializing Tmux..."
 echo

 local TPM_DIR="$TMUX_DST_DIR/plugins/tpm"
 local PLUGINS_DIR="$TMUX_DST_DIR/plugins"

 log "🗄️  Saving tmux path to $TMUX_DST_DIR/.tmux_meta"
 echo "$TMUX_DST_DIR" >"$TMUX_DST_DIR/.tmux_meta"

 log "🗑️  Clearing temporary caches..."

 echo
 safe_execute "rm -rf /tmp/tmux" 2>/dev/null
 safe_execute "mkdir -p \"$TMUX_DST_DIR\""

 log "💾 Installing TPM..."
 safe_execute "cp -raf \"$SRC_DIR/.config/tmux/.\" \"$TMUX_DST_DIR/\""
 safe_execute "chmod -R 755 \"$PLUGINS_DIR\""

 # TPM requires plugin scripts (*.tmux) to be executable to auto-load.
 if [[ -d "$PLUGINS_DIR" ]]; then
  log "🛂  Setting executable permissions for plugins..."
  safe_execute "chmod -R 755 \"$PLUGINS_DIR\""
 fi

 if [[ -x "$TPM_DIR/bin/install_plugins" ]]; then
  log "💾  Installing plugins..."
  safe_execute "\"$TPM_DIR/bin/install_plugins\" >/dev/null 2>&1"
 fi
}

# Resolve location, handling symlinks
function current-location {

 SOURCE="${BASH_SOURCE[0]}"

 while [ -h "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE"
 done

 DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
 echo "$DIR"
}

function pre_flight_check() {

 # Ensure that Tmux isn't running
 if [[ -v TMUX ]]; then
  echo -e "(!) \e[1;93mQuit Tmux before proceeding\e[0m"
  echo -e "    \e[90mCommand:\e[0m \e[38;2;232mpkill -f tmux\e[0m"
  echo
  exit 1
 fi
}

function initialize() {

 pre_flight_check

 check_dependencies

 # Skip prompt in dry run
 if [[ "$DRY_RUN" == "false" ]]; then
  read -r -p "Continue with initialization? (y/n): " answer
  if [[ "$answer" != "y" ]]; then
   log "Terminating..."
   exit 0
  fi
 fi

 # --- Bashrc Handling ---
 if [[ -L "$HOME/.bashrc" ]]; then
  log "🛈︎  .bashrc is already a symlink. Skipping."
 else
  log "⛃ Backing up existing ~/.bashrc to $BACKUP_PATH"
  safe_execute "tar -cf \"$BACKUP_PATH\" \"$HOME/.bashrc\" 2>/dev/null || true"

  log "🗑️  Removing existing bashrc..."
  safe_execute "rm -f \"$HOME/.bashrc\""
  safe_execute "ln -s \"$SRC_DIR/.bashrc\" \"$HOME/.bashrc\""
 fi

 if [[ -L "$HOME/.bashrc_aliases" ]]; then
  log "🛈︎  .bashrc_aliases is already a symlink :: Skipping."
 else
  log "⛃  Backing up existing ~/.bashrc_aliases to $BACKUP_PATH"
  safe_execute "tar -cf \"$BACKUP_PATH\" \"$HOME/.bashrc_aliases\" 2>/dev/null || true"

  log "🗑️  Removing existing bashrc_aliases..."
  safe_execute "rm -f \"$HOME/.bashrc_aliases\""
  safe_execute "ln -s \"$SRC_DIR/.bashrc_aliases\" \"$HOME/.bashrc_aliases\""
 fi

 if [[ -L "$HOME/.bashrc_functions" ]]; then
  log "🛈︎  .bashrc_functions is already a symlink. Skipping."
 else
  log "⛃  Backing up existing ~/.bashrc_functions to $BACKUP_PATH"
  safe_execute "tar -cf \"$BACKUP_PATH\" \"$HOME/.bashrc_functions\" 2>/dev/null || true"

  log "🗑️  Removing existing bashrc_functions..."
  safe_execute "rm -f \"$HOME/.bashrc_functions\""
  safe_execute "ln -s \"$SRC_DIR/.bashrc_functions\" \"$HOME/.bashrc_functions\""
 fi

 # --- Tmux Config Handling ---
 local possible_paths=("$HOME/.config/tmux" "$HOME/.tmux" "$HOME/.tmux.conf")

 for possible in "${possible_paths[@]}"; do
  if [[ -e "$possible" ]]; then
   log "🔎  Found existing config: $possible. Backing up..."
   safe_execute "tar -rf \"$BACKUP_PATH\" \"$possible\" 2>/dev/null"
   safe_execute "rm -rf \"$possible\""
  fi
 done

 safe_execute "mkdir -p \"$TMUX_DST_DIR\""
 log "📂  Copying new tmux configuration..."

 if [[ -d "$SRC_DIR/.config/tmux" ]]; then
  safe_execute "cp -raf \"$SRC_DIR/.config/tmux\" \"$TMUX_DST_DIR/\""
 else
  log "⚠️   Warning: Source config directory '$SRC_DIR/.config/tmux' not found."
 fi

 # Call tmux_fix function
 tmux_fix

 # Call install_fonts function
 install_fonts

 # --- Sourcing files ---
 local white_list_files=(".bashrc_packages" ".bashrc_aliases" ".bashrc_functions" ".bashrc_completions")

 for file in "${white_list_files[@]}"; do
  if [[ -f "$SRC_DIR/$file" ]]; then
   if [[ "$DRY_RUN" == "true" ]]; then
    log "🪄  [DRY RUN] Source: $SRC_DIR/$file"
   else
    # shellcheck disable=SC1090
    source "$SRC_DIR/$file"
   fi
  fi
 done

 SRC_MEDIA_DIR="$SRC_DIR/os-mods/audio"
 DST_MEDIA_DIR="/opt/audio"

 # Make sure it exists
 safe_execute "mkdir -p \"$DST_MEDIA_DIR\""

 for font in "$SRC_MEDIA_DIR"/*; do
  log "📁  [DRY RUN] Copying font \"$SRC_MEDIA_DIR\" to \"$DST_MEDIA_DIR\""
 done

 log "📂  Copying new tmux configuration..."

 if [[ -d "$SRC_MEDIA_DIR" ]]; then
  safe_execute "sudo cp -rfT \"$SRC_MEDIA_DIR\" \"$DST_MEDIA_DIR\""
  safe_execute "sudo chown -R $USER:$USER \"$DST_MEDIA_DIR\""
 else
  log "⚠️   Warning: Source media directory \"$SRC_MEDIA_DIR\" not found."
 fi

 log "👍  Environment Initialized Successfully!"

 if [[ -z "${TMUX:-}" ]]; then
  safe_execute "tmux -f \"$TMUX_DST_DIR/tmux.conf\""
 else
  safe_execute "tmux source-file \"$TMUX_DST_DIR/tmux.conf\""
 fi
}

function start_dry_run() {

 echo
 echo "=========================================="
 echo "🚧       STARTING DRY-RUN MODE          🚧"
 echo "=========================================="
 echo

 DRY_RUN="true"
 initialize

 echo
 echo "=========================================="
 echo "🏁       DRY-RUN MODE COMPLETE          🏁"
 echo "=========================================="
 echo
}

# --- Main Entry Point Logic ---
if [[ "${1:-}" == "--dry-run" ]]; then
 start_dry_run
else
 echo -e "\e[90m(i) Initialization Dev Environment...\e[0m"
 initialize
fi
