#!/bin/bash

################################################
# ALIASES                                      #
################################################

SCRIPT_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# This env must be set for proper navigation
DEV_HOME=${DEV_HOME}

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# system tool aliases
alias ll='ls -alF --color=always'
alias la='ls -A --color=always'
alias l='ls -CF --color=always'

# dev tool alias
alias t="tmux"
alias edit="gnome-text-editor"
alias mk="minikube"

tmux_conf="$HOME/.config/tmux/tmux.conf"
if [[ -f "$tmux_conf" ]]; then
 alias source-t="tmux source-file $tmux_conf"
else
 alias source-t="tmux source-file"
fi

bat_variants=("bat" "batcat")
for variant in "${bat_variants[@]}"; do
 if command -v "$variant" >/dev/null 2>&1; then
  alias bat="$variant --style=full"
 fi
done

if [[ -d "$DEV_HOME" ]]; then
 alias denv="cd $DEV_HOME"
else
 echo -e " (\e[91m!\e[0m) The dev.environment env was not found"
 exit 1
fi

# kubernetes aliases
alias k='kubecolor'
alias v="vim"
alias tf='terraform'
#alias k9s='k9s --headless'
#alias k9='k9s --headless'
alias k9s='k9s -A -c pods --headless'
alias kubectl="kubecolor"
alias pods="kubectl get pods -A"
alias deploys="kubectl get deploy -A"
alias sas="kubectl get sa -A"
alias pvs="kubectl get pv -A"
alias pvcs="kubectl get pvc -A"
alias svcs="kubectl get svc -A"
alias watch-pods="watch -n 1 'kubectl get pods -A'"
alias watch-deploys="watch -n 1 'kubectl get deploy -A'"
alias watch-svcs="watch -n 1 'kubectl get svc -A'"
alias current-context="kubectl config current-context"
alias contexts="kubectl config get-contexts"

# Git aliases
alias groot='cd $(git rev-parse --show-toplevel)'
