#!/bin/bash

# If not a human/interactively, don't do anything
case $- in
*i*) ;;
*)
 return
 ;;
esac

# Set system config location
export XDG_CONFIG_HOME="$HOME/.config"

# Set default file editor
export EDITOR=vim
export KUBE_EDITOR=vim

# Set default file viewr
export VISUAL=bat

# Set K9s NodeShell Active
export K9S_FEATURE_GATE_NODE_SHELL=true

# Set k9s Plugin Directory
export K9S_CONFIG_DIR="$HOME/.config/k9s"

# Bash history control
HISTCONTROL=ignoreboth
HISTSIZE=10000

# Don't create a less history file
export LESSHISTFILE="$XDG_CONFIG_HOME/.less_history"
export HISTFILE="$XDG_CONFIG_HOME/.bash_history"

# Change fzy search to select multiple with spacebar
export FZF_DEFAULT_OPTS="--bind 'space:toggle-in'"

shopt -s histappend

# Add directory to PATH
if [ -d "$HOME/.local/bin" ]; then
 export PATH="$HOME/.local/bin:$PATH"
fi

# Check the window size after each command
shopt -s checkwinsize

################################################
#          Shell Configuruation                #
################################################

# make less more friendly for non-text input
if [ -x /usr/bin/lesspipe ]; then
 eval "$(SHELL=/bin/sh lesspipe)"
fi

############################################
#           Bash Resource Files            #
############################################

source ~/.bash_aliases
source ~/.bash_functions
source ~/.bash_completions

############################################
#           TERMINAL FUNCTIONS             #
############################################

RED="\[\e[38;5;196m\]"
GREEN="\[\e[38;5;84m\]"
BRIGHT_GREEN="\[\e[38;5;216m\]"
YELLOW="\[\e[0;33m\]"
BLUE="\[\e[0;34m\]"
MAGENTA="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
END="\[\e[0m\]"

update_prompt_string() {

 local EXIT_CODE=$?

 if [[ "$EXIT_CODE" -eq 0 ]]; then
  PS1="${GREEN} ➤  ${END}"
 else
  PS1="${RED} ➤💥  ${END}"
 fi
}

# Bash terminal prompt session
export PS1='${BRIGHT_GREEN} ➤  ${END}'

# Execute the dynamic prompt update (Function defined in bashrc_functions)
export PROMPT_COMMAND=update_prompt_string

################################################
# BASH AUTO UPDATE                             #
################################################

function update-system {
 sudo apt update &&
  sudo apt full-upgrade -y &&
  sudo apt autoremove -y &&
  sudo apt autoclean
}

function system-update {
 update-system "$@"
}

################################################
# BASH AUTO COMPLETE                           #
################################################

# Kubectl auto-complete
if command -v kubectl >/dev/null; then
 source <(kubectl completion bash)
 complete -o default -F __start_kubectl k
fi

# Load Bash tab completion
if ! shopt -oq posix; then
 if [ -f /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
 elif [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
 fi
fi

################################################
# CONFIGURATION & HOOKS                        #
################################################

# Terminal Sound Fx
function terminal_soundFx {

 local action="$1"

 # Check if argument count is 0
 if [[ "$#" -eq 0 && -n "$PS1" ]]; then
  echo -e "${GRAY}(!) SoundFx: No action specified${END}"
  return 1
 fi

 declare -A actions
 actions["open"]="$HOME/.local/share/audio/info.mp3"
 actions["close"]="$HOME/.local/share/audio/MegamanTeleport.wav"

 # 3. Check if the action exists in the map
 if [[ -z "${actions[$action]}" ]]; then
  echo -e "${GRAY}(!) SoundFx: Action Unknown '$action'${END}"
  return 1
 fi

 local sound_file="${actions[$action]}"

 # Check if file exists (AND check for mpv)
 if [[ ! -f "$sound_file" ]]; then
  return 1
 fi

 # Check for mpv command
 if ! command -v mpv >/dev/null; then
  return 1
 fi

 # Play Sound
 nohup mpv "$sound_file" >/dev/null 2>&1 &
 disown
}

# Play Open Sound
terminal_soundFx open

# Trap Close Sound
trap 'terminal_soundFx close' EXIT
