#!/bin/bash

TARGET_DIR="$PWD/resources"
VIM_ROOT="$TARGET_DIR/.vim"
AUTOLOAD_DIR="$VIM_ROOT/autoload"
PLUGGED_DIR="$VIM_ROOT/plugged"

# CLEANUP AND SETUP
echo "[+] Cleaning up old builds..."
rm -rf "$TARGET_DIR"

echo "[+] Creating directory structure..."
mkdir -p "$AUTOLOAD_DIR"
mkdir -p "$PLUGGED_DIR"

echo "[+] Downloading plug.vim..."
curl -fLo "$AUTOLOAD_DIR/plug.vim" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "[+] Cloning plugins into local directory..."
clone_plugin() {
 REPO_URL=$1
 DIR_NAME=$2
 echo "    - Cloning $DIR_NAME..."
 git clone --depth 1 "$REPO_URL" "$PLUGGED_DIR/$DIR_NAME" >/dev/null 2>&1
 rm -rf "$PLUGGED_DIR/$DIR_NAME/.git"
}

clone_plugin "https://github.com/preservim/nerdtree.git" "nerdtree"
clone_plugin "https://github.com/junegunn/fzf.vim.git" "fzf.vim"
clone_plugin "https://github.com/vim-airline/vim-airline.git" "vim-airline"
clone_plugin "https://github.com/morhetz/gruvbox.git" "gruvbox"
clone_plugin "https://github.com/sheerun/vim-polyglot.git" "vim-polyglot"

echo "[+] Handling FZF (Fuzzy Finder)..."
clone_plugin "https://github.com/junegunn/fzf.git" "fzf"

FZF_BIN_URL="https://github.com/junegunn/fzf/releases/download/0.50.0/fzf-0.50.0-linux_amd64.tar.gz"
FZF_DEST="$PLUGGED_DIR/fzf/bin"

echo "[+] Creating directory structure..."
mkdir -p "$FZF_DEST"

echo "[+] Downloading FZF binary..."
curl -L "$FZF_BIN_URL" -o fzf.tar.gz
tar -xzf fzf.tar.gz
mv fzf "$FZF_DEST/"
rm fzf.tar.gz
chmod +x "$FZF_DEST/fzf"

echo "[+] Generating .vimrc configuration..."
cat <<'EOF' >"$TARGET_DIR/.vimrc"

" This MUST be the first line
set nocompatible

call plug#begin('~/.vim/plugged')
 Plug 'preservim/nerdtree'
 Plug 'junegunn/fzf'
 Plug 'junegunn/fzf.vim'
 Plug 'vim-airline/vim-airline'
 Plug 'morhetz/gruvbox'
 Plug 'sheerun/vim-polyglot'
call plug#end()

" General User Interface ---
" Enable syntax highlighting based on file type
syntax on
" Show line numbers on the left sidebar
set number
" Show the line number relative to the line the cursor is on
set relativenumber
" Highlight the line currently under the cursor for better visibility
set cursorline
" Wrap lines that are longer than the screen width
set wrap
" Don't make a backup file before overwriting a file
set nobackup
" Don't create a swap file for the current buffer
set noswapfile
" Indentation & Tabs ---
" Copy indent from the current line when starting a new line
set autoindent
" Enable smart indentation (e.g., indenting automatically after a '{')
set smartindent
" Convert tabs to spaces (standard for most modern coding styles)
set expandtab
" The number of spaces inserted for each indentation level
set shiftwidth=4
" The number of spaces a <Tab> counts for
set tabstop=4
" When pressing <Tab> or <Backspace>, treat spaces like a tab
set softtabstop=4
" Search Behavior ---
" Highlight all search matches
set hlsearch
" Show search matches as you type
set incsearch
" Ignore case when searching
set ignorecase
" Override 'ignorecase' if the search pattern contains uppercase characters
set smartcase
" Usability & Navigation ---
" Allow hidden buffers (opening a new file without saving current one)
set hidden
" Enable mouse support in all modes
set mouse=a
" Keep 8 lines of context above/below the cursor when scrolling
set scrolloff=8
" Display incomplete commands in the bottom right corner
set showcmd
" Enhanced command-line completion menu
set wildmenu
" Reduce screen redraws during macros
set lazyredraw
" Allow backspacing over auto-indentation, line breaks, and start of insert
set backspace=indent,eol,start
" Key Mappings ---
let mapleader = " "
inoremap jj <Esc>
nnoremap <leader><space> :nohlsearch<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
" Plugin Settings ---
" NERDTree Toggle ---
nnoremap <C-n> :NERDTreeToggle<CR>
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
" FZF Finder ---
nnoremap <C-p> :Files<CR>
" Theme ---
set background=dark
try
 colorscheme gruvbox
catch
 colorscheme default
endtry
EOF

echo "[+] Generating 'vim-install' script..."

cat <<'EOF' >"vim-install"
#!/bin/bash

echo "Installing vim config---"

# Install new configs
cp -r resources/.vim "$HOME/.vim"
cp resources/.vimrc "$HOME/.vimrc"
EOF

chmod +x "vim-install"
