#!/bin/bash

echo "Installing xserver synaptic inputs"
sudo apt install xserver-xorg-input-synaptics

echo "Setting up touch-pad settings to enable two-finger scrolling"
synclient VertTwoFingerScroll=1

echo "Enabeling gnome two-finger-scrolling"
gsettings set org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled true

read -r -p "Log out now? (y/n) : " response

if [[ "$response" == "y" ]]; then
 sudo pkill -u $USER
else
 echo "Logout for changes to take effect"
fi
