#!/bin/bash

if ! command -v git > /dev/null 2>&1; then
 sudo apt install git
fi

git config --global user.name "xxx"
git config --global user.email "xxx@xxx.com"
git config --global init.defaultBranch main
git config --global color.ui auto
git config --global core.editor "vim"

# 3. Pull & Push Behavior
git config --global pull.rebase true
git config --global push.autoSetupRemote true
git config --global fetch.prune true
git config --global merge.conflictstyle diff3
git config --global alias.st status
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
git config --global alias.unstage 'reset HEAD --'

echo "Git configuration complete!"
